theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  analytics:
    gtag: G-Y88LQ85YZ1
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
#  - offline
#  - def_list
#  - pymdownx.tasklist:
#      custom_checkbox: true
  - search

  - autorefs
#  - attr_list
#  - autozip:
#      # TODO: find a way to use $READTHEDOCS_OUTPUT and $READTHEDOCS_PROJECT
#      # source_zip_dir: $READTHEDOCS_OUTPUT
#      # source_zip_file_name: $READTHEDOCS_PROJECT.zip
#      source_zip_dir: ../htmlzip/
#      source_zip_file_name: test-builds.zip
#      add_source_zip_to_nav: false
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
  - with-pdf :
      cover_subtitle: PDF created with mkdocs-with-pdf
      # TODO: find a way to use $READTHEDOCS_OUTPUT and $READTHEDOCS_PROJECT
      # output_path: $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT.pdf
      output_path: builds.pdf

site_name: CnC Tools and Resources
site_description: A series of resources for mappers and linux users for WW 2.5D games
#site_url: https://cattanker.github.io/CnC-Resource-Docs/
repo_url: https://github.com/CatTanker/cnc_map_tool_guide
repo_name: Documentation Github Page
nav:
#  - Home: home.md redundant, since index.md seems to be hardcoded
  - Landing Page: index.md
  - 'Mapping Tools':
    - 'Core Tools': 'core_editors.md'
    - 'Modern Options': 'modern_editors.md'
    - 'Assistive Tools': 'additional_tools.md'
  - 'Resources':
    - 'Mapping': 'mapresources.md'
    - 'Renderers': 'rendererresources.md'
    - 'Support' : 'generalsupport.md'
  - 'Linux Resources':
    - 'Introduction': 'linuxintro.md'
    - 'Bottles': 'bottles.md'
    - 'WineTricks' : 'winetricks.md'
    - 'Support and Compatability' : 'linuxsupport.md'
    - 'Editor Tool Compatability' : 'linuxtools.md'
extra:
  analytics:
    provider: google
    property: G-Y88LQ85YZ1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by commenting any issues onto GitHub.
  consent:
    title: Cookie consent
    description: >-


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
