theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
#  - offline
#  - def_list
#  - pymdownx.tasklist:
#      custom_checkbox: true
  - search

  - autorefs
#  - attr_list
#  - autozip:
#      # TODO: find a way to use $READTHEDOCS_OUTPUT and $READTHEDOCS_PROJECT
#      # source_zip_dir: $READTHEDOCS_OUTPUT
#      # source_zip_file_name: $READTHEDOCS_PROJECT.zip
#      source_zip_dir: ../htmlzip/
#      source_zip_file_name: test-builds.zip
#      add_source_zip_to_nav: false
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
  - with-pdf :
      cover_subtitle: PDF created with mkdocs-with-pdf
      # TODO: find a way to use $READTHEDOCS_OUTPUT and $READTHEDOCS_PROJECT
      # output_path: $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT.pdf
      output_path: builds.pdf

site_name: CnC Tools and Resources
site_description: A series of resources for mappers and linux users for WW 2.5D games
#site_url: https://cattanker.github.io/CnC-Resource-Docs/
repo_url: https://github.com/CatTanker/cnc_map_tool_guide
repo_name: Documentation Github Page
nav:
#  - Home: home.md redundant, since index.md seems to be hardcoded
  - Landing Page: index.md
  - 'Mapping Tools':
    - 'Core Tools': 'core_editors.md'
    - 'Modern Options': 'modern_editors.md'
    - 'Assistive Tools': 'additional_tools.md'
  - Map Resources: resources.md
  - 'Linux Resources':
    - 'Introduction': 'linuxintro.md'
    - 'Bottles': 'bottles.md'
    - 'WineTricks' : 'winetricks.md'
    - 'Support and Compatability' : 'linuxsupport.md'
    - 'Editor Tool Compatability' : 'linuxtools.md'
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
      name: squidfunk on Fosstodon
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
